CURRENT_POLICY_PARAMS = {
    "reform_current_policy": {
        "salt_caps": {
            "JOINT": 10_000,
            "SEPARATE": 5_000,
            "SINGLE": 10_000,
            "HEAD_OF_HOUSEHOLD": 10_000,
            "SURVIVING_SPOUSE": 10_000,
        },
        "amt_exemptions": {
            "JOINT": 140_565,
            "SEPARATE": 70_283,
            "SINGLE": 90_394,
            "HEAD_OF_HOUSEHOLD": 90_394,
            "SURVIVING_SPOUSE": 90_394,
        },
        "amt_phase_outs": {
            "JOINT": 1_285_409,
            "SEPARATE": 642_705,
            "SINGLE": 642_705,
            "HEAD_OF_HOUSEHOLD": 642_705,
            "SURVIVING_SPOUSE": 642_705,
        },
        "salt_phase_out_enabled": False,
        "salt_phase_out_rate": 0,
        "salt_phase_out_threshold_joint": 0,
        "salt_phase_out_threshold_other": 0,
        "other_tcja_provisions": True,
    }
}

DARK_GRAY = "rgba(74, 74, 74, 0.9)"  # More transparent dark gray
BLUE = "#3378b2"
RED = "#f45959"
LIGHT_GRAY = "#bababa"

STATE_CODES = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
]
